Automatic Binning
GeoStat-Framework/GSTools pull request #131
Opened 2021-01-14 12:07 UTC by MuellerSeb

Closes: #55 #36 

This PR adds a simple automatic binning routine `standard_bins` to the variogram submodule.
It returns an equal division from 0 to `max_dist` with `bin_no` as number of bins. The following rules are applied:
- if `max_dist` is not given, it is set to one third of the box diameter
- if `bin_no` is not given, it is determined by sturges' rule from the number of point combinations

You can now call `gs.vario_estimate` without passing `bin_edges`. In this case, the bin_edges will be determined as described above.

2021-01-14 17:49 UTC, MuellerSeb commented
@LSchueler ready for review. :blush:

2021-01-15 11:39 UTC, LSchueler commented on examples/03_variogram/06_auto_bin_latlon.py
> +# is straight forward with GSTools. ;-)
Really nice example!

2021-01-15 11:45 UTC, LSchueler requested changes
This is a really nice convenience addition!

What do you think of moving the `_chordal_to_great_circle` method to a more visible place and making it public?

Appart from that, I think we are ready to merge this PR.

2021-01-15 11:45 UTC, LSchueler commented on gstools/variogram/binning.py
> +    return 2 * np.arcsin(np.minimum(np.maximum(np.divide(dist, 2), 0), 1))
I think this could be put into `gstools/tools`.

2021-01-15 12:08 UTC, LSchueler commented
I fixes some typos, so don't forget to pull.

2021-01-15 19:52 UTC, MuellerSeb commented on examples/03_variogram/06_auto_bin_latlon.py
> +# is straight forward with GSTools. ;-)
:blush:

2021-01-15 20:14 UTC, MuellerSeb commented
Strange. It was merged, but this PR says it has conflicts and can't be merged. It felt like an internal GitHub Error when I clicked on "merge" and I had to reload the page. Hope nothing was broken.

2021-01-15 20:14 UTC, closed without merging