setuptools: move project data to pyproject.toml
GeoStat-Framework/GSTools pull request #241
Opened 2022-05-27 18:13 UTC by MuellerSeb

TODO

2022-05-27 22:51 UTC, MuellerSeb commented
OpenMP support was never available in CI for macOS. There is also an open PR for clang/openmp support on macOS here: https://github.com/astropy/extension-helpers/pull/42

We could wait for this PR to be merged and then we could install openmp with brew for macOS:
```yml
      - name: macos openmp install
        uses: mstksg/get-package@v1
        if: matrix.os == 'macos-latest'
        with:
          brew: libomp
```

2022-06-09 10:30 UTC, LSchueler requested changes
That's a nice improvement in the setup! A small fix in the toml-file and you're ready to merge this :+1:

2022-06-09 10:30 UTC, LSchueler commented on pyproject.toml
> +    "Programming Language :: Python :: 3.6",
Drop this line

2022-06-09 10:44 UTC, MuellerSeb commented
When this is implemented, we can even drop the `MANIFEST.in`: https://github.com/pypa/setuptools/issues/3341

2022-06-13 11:18 UTC, merged