Add sum model
GeoStat-Framework/GSTools pull request #364
Opened 2024-08-11 15:05 UTC by MuellerSeb

TODO

2025-02-08 13:12 UTC, MuellerSeb commented
@LSchueler this is ready for review.

2025-02-10 11:41 UTC, LSchueler commented
Awesome, I'll need some time to thoroughly go throw your changes.
But I already saw that you claimed example number 11 for the sum model after I did the same for the plurigaussian fields :-D Do we just keep adding new examples in an ascending order according to the time a PR is merged?

2025-02-10 11:43 UTC, MuellerSeb commented
First come, first serve :-D

2025-03-23 20:49 UTC, LSchueler requested changes
Sorry for taking so long to finish this review, but as you know, I had the best reasons ;-)

I'm really looking forward to sum models being integrated into GSTools, but I found quite a few things which should be addressed before merging.

2025-03-23 20:49 UTC, LSchueler commented on src/gstools/covmodel/sum_tools.py
> +        msg = "SumModel.set_len_weights: skipped length scales to big."
Please fix grammar

2025-03-23 20:49 UTC, LSchueler commented on src/gstools/covmodel/fit.py
> +def _check_sill(model, para_select, sill, bnd, sum_cfg):
Please add a short description of what exactly is checked.

2025-03-23 20:49 UTC, LSchueler commented on src/gstools/covmodel/fit.py
> +        model.nugget = nugget
There are quite a few pretty large `if is_sum` branches all over the place here. Maybe you can find a better structure for the code in this module?

2025-04-22 14:20 UTC, MuellerSeb commented on examples/11_sum_model/01_fitting_sum_model.py
> +# scales of the individual models can be accessed by the attributes
But the variances and length scales are handled differently, since they are stored as a list defining the ratios between the models. So I would keep it like this.

2025-04-22 19:16 UTC, MuellerSeb commented on src/gstools/covmodel/fit.py
> +        model.nugget = nugget
I think this is a task for the future to rework the fitting in general. I think a class for a variogram fitter could be helpful to not pass around all the the information over and over again.

For now I would keep it like this.

2025-04-22 19:24 UTC, MuellerSeb commented on src/gstools/covmodel/fit.py
> +        model.nugget = nugget
See #382

2025-04-22 19:25 UTC, MuellerSeb commented
@LSchueler fixed (almost) all your complains. Second look? :upside_down_face:

2025-04-27 19:32 UTC, LSchueler commented on tests/test_sum_model.py
:-D This diff looks pretty funny. The easiest refactoring ever?! ;-)

2025-04-28 05:56 UTC, MuellerSeb commented on tests/test_sum_model.py
Jepp :joy:

2025-04-28 06:43 UTC, MuellerSeb commented
# LGTM :tada:

2025-04-28 06:43 UTC, merged